[project]
name = "kirkify"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.6"
dependencies = [
    "numpy==1.24.3",
    "opencv-python==4.8.1.78",
    "pygame==2.5.2",
    "requests==2.31.0",
]
